#!/bin/sh
set -e
cd "$(dirname "$0")"
rm -rf entropy_artifacts portage_artifacts
source ./setup-build-environment
sabayon-buildpackages x11-misc/xss-lock
sabayon-buildpackages x11-misc/sxlock --layman andjscott
sabayon-buildpackages net-misc/dropbox-cli
sabayon-buildpackages sys-apps/findutils-glocate
sabayon-createrepo
